name: example
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Other
  logger: ^1.1.0
  rxdart: ^0.27.7

  utils:
    git:
      url: https://github.com/altynbek132/utils.git
  # State manager
  mobx:
    git:
      url: https://github.com/altynbek132/utils.git
      path: packages/mobx-2.1.1
  flutter_mobx:
    git:
      url: https://github.com/altynbek132/utils.git
      path: packages/flutter_mobx-2.0.6+4
  provider: ^6.0.5

  dart_json_mapper: ^2.2.5+1
  dart_json_mapper_mobx:
    git:
      url: https://github.com/altynbek132/utils.git
      path: packages/dart_json_mapper_mobx-2.0.5
  dart_json_mapper_flutter: ^2.0.1
  dio: ^4.0.6
  tuple: ^2.0.1
  bottom_sheet: ^3.1.2
  awesome_extensions: ^1.0.1

  go_router: ^5.2.4
  easy_dispose: ^1.1.0
  easy_dispose_flutter: ^1.1.0
  easy_dispose_rxdart: ^1.1.0
  cached_network_image: ^3.2.3
  bloc: ^8.1.0
  disposing: ^1.0.3+1
  disposing_flutter:
    git:
      url: https://github.com/SKKbySSK/dart_disposing.git
      path: disposing_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # Generators
  build_verify: ^3.1.0
  build_runner: ^2.3.0
  dart_code_metrics: ^4.19.2
  mobx_codegen:
    git:
      url: https://github.com/altynbek132/utils.git
      path: packages/mobx_codegen-2.1.0


flutter:

  uses-material-design: true
