name: deobfuscate_js_stacktrace
version: 1.0.0

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

  path: ^1.8.0
  source_map_stack_trace: any
  source_maps: any
  stack_trace: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
