name: utils_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # State manager
  mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx
  disposing:
    git:
      url: https://github.com/altynbek132/dart_disposing
      path: packages/disposing

  logger: ^2.0.0
  rxdart: ^0.27.7
  dio: ^5.4.0
  get_it: ^7.6.7
  platform_info: ^4.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
