name: utils_flutter
description: A new Flutter package project.
version: 2.0.2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx

dependencies:
  flutter:
    sdk: flutter

  # State manager
  #! override
  mobx: any
  flutter_mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: flutter_mobx
  disposing:
    git:
      url: https://github.com/altynbek132/dart_disposing
      path: packages/disposing
  elementary:
    git:
      url: https://github.com/altynbek132/flutter-elementary
      path: packages/elementary

  # Other
  logger: ^2.0.0
  rxdart: ^0.27.7
  provider: ^6.1.0
  dio: ^5.4.0
  get_it: ^7.6.7
  platform_info: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9

  flutter_lints: ^3.0.1

  # Generators
  build_runner: ^2.4.8
  dart_code_metrics: ^5.7.6
  mobx_codegen:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx_codegen
