include: package:flutter_lints/flutter.yaml

#  // ignore: name_of_lint
#  // ignore_for_file: name_of_lint

analyzer:
  exclude:
    - /**/_old/**
    - /**/no_lint_*
    - packages

linter:
  # true - active
  # false - inactive
  rules:
    unnecessary_brace_in_string_interps: false
    library_private_types_in_public_api: false
    empty_catches: false
    unused_local_variable: false
    use_build_context_synchronously: false
    avoid_print: false
